export const STOCK_LIST_REQUEST = 'STOCK_LIST_REQUEST';
export const STOCK_LIST_SUCCESS = 'STOCK_LIST_SUCCESS';
export const STOCK_LIST_FAIL = 'STOCK_LIST_FAIL';
export const SAVED_STOCK_ADD = 'SAVED_STOCK_ADD';
export const SAVED_STOCK_REMOVE = 'SAVED_STOCK_REMOVE';
export const SAVED_STOCK_FAIL = 'SAVED_STOCK_FAIL';
